# Generated by Django 3.2.7 on 2021-10-16 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20211016_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 7, 19, 1, 906387, tzinfo=utc)),
        ),
    ]
