# Generated by Django 3.2.7 on 2021-10-16 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211016_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_details',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 7, 18, 34, 730376, tzinfo=utc)),
        ),
    ]
